### PR TITLE
Remove README.md

### PR DESCRIPTION
**Pull request by tomwilkie**
https://github.com/mwitkow/go-grpc-middleware/commit/e25b7320bd2baf4a5843c035778ae73cc4b88b76 added README.md, where a README.MD already exists.  This doesn't play well on macs, with their case insensitive FS.

### CODE REVIEW

**Comment by tomwilkie** [comment]
See https://github.com/golang/dep/issues/365 for the problem I hit.

**Comment by mwitkow** [comment]
Can you make this move the README.MD to README.md content so that the `fixup.sh` script detects it? :)

**Comment by tomwilkie** [comment]
Sure!

**Comment by mwitkow** [comment]
Cheers!

**Pull request merged**
